//
//  AppleReposMock.swift
//  AcademyChallengeApp
//
//  Created by Rúben Antunes on 19/10/2022.
//

import Foundation

class AppleReposMock {
    var mockedAppleRepos: [AppleRepos] = [
            AppleRepos(id: 1, fullName: "Repos 1", isPrivate: true),
            AppleRepos(id: 2, fullName: "Repos 2", isPrivate: true),
            AppleRepos(id: 3, fullName: "Repos 3", isPrivate: true),
            AppleRepos(id: 4, fullName: "Repos 4, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 5, fullName: "Repos 5", isPrivate: true),
            AppleRepos(id: 6, fullName: "Repos 6", isPrivate: true),
            AppleRepos(id: 7, fullName: "Repos 7, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 8, fullName: "Repos 8", isPrivate: true),
            AppleRepos(id: 9, fullName: "Repos 9, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 10, fullName: "Repos 10", isPrivate: true),
            AppleRepos(id: 11, fullName: "Repos 11", isPrivate: true),
            AppleRepos(id: 12, fullName: "Repos 12, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 13, fullName: "Repos 13", isPrivate: true),
            AppleRepos(id: 14, fullName: "Repos 14, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 15, fullName: "Repos 15", isPrivate: true),
            AppleRepos(id: 16, fullName: "Repos 16", isPrivate: true),
            AppleRepos(id: 17, fullName: "Repos 17", isPrivate: true),
            AppleRepos(id: 18, fullName: "Repos 18, This a test to verify if the cell resizes by itself", isPrivate: true),
            AppleRepos(id: 19, fullName: "Repos 19", isPrivate: true),
            AppleRepos(id: 20, fullName: "Repos 20", isPrivate: true),
            AppleRepos(id: 21, fullName: "Repos 21", isPrivate: true),
            AppleRepos(id: 22, fullName: "Repos 22", isPrivate: true),
            AppleRepos(id: 23, fullName: "Repos 23, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 24, fullName: "Repos 24", isPrivate: true),
            AppleRepos(id: 25, fullName: "Repos 25", isPrivate: true),
            AppleRepos(id: 26, fullName: "Repos 26, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 27, fullName: "Repos 27", isPrivate: true),
            AppleRepos(id: 28, fullName: "Repos 28", isPrivate: true),
            AppleRepos(id: 29, fullName: "Repos 29", isPrivate: true),
            AppleRepos(id: 30, fullName: "Repos 30, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 31, fullName: "Repos 31", isPrivate: true),
            AppleRepos(id: 32, fullName: "Repos 32, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 34, fullName: "Repos 34", isPrivate: true),
            AppleRepos(id: 35, fullName: "Repos 35, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 36, fullName: "Repos 36", isPrivate: true),
            AppleRepos(id: 37, fullName: "Repos 37", isPrivate: true),
            AppleRepos(id: 38, fullName: "Repos 38, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 39, fullName: "Repos 39", isPrivate: true),
            AppleRepos(id: 40, fullName: "Repos 40", isPrivate: true),
            AppleRepos(id: 41, fullName: "Repos 41, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 42, fullName: "Repos 42", isPrivate: true),
            AppleRepos(id: 43, fullName: "Repos 43", isPrivate: true),
            AppleRepos(id: 44, fullName: "Repos 44, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 45, fullName: "Repos 45", isPrivate: true),
            AppleRepos(id: 46, fullName: "Repos 46", isPrivate: true),
            AppleRepos(id: 47, fullName: "Repos 47", isPrivate: true),
            AppleRepos(id: 48, fullName: "Repos 48, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 49, fullName: "Repos 49", isPrivate: true),
            AppleRepos(id: 50, fullName: "Repos 50", isPrivate: true),
            AppleRepos(id: 51, fullName: "Repos 51, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 52, fullName: "Repos 52", isPrivate: true),
            AppleRepos(id: 53, fullName: "Repos 53", isPrivate: true),
            AppleRepos(id: 54, fullName: "Repos 54, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 55, fullName: "Repos 55", isPrivate: true),
            AppleRepos(id: 56, fullName: "Repos 56", isPrivate: true),
            AppleRepos(id: 57, fullName: "Repos 57", isPrivate: true),
            AppleRepos(id: 58, fullName: "Repos 58, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 59, fullName: "Repos 59", isPrivate: true),
            AppleRepos(id: 60, fullName: "Repos 60", isPrivate: true),
            AppleRepos(id: 61, fullName: "Repos 61, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 62, fullName: "Repos 62", isPrivate: true),
            AppleRepos(id: 63, fullName: "Repos 63", isPrivate: true),
            AppleRepos(id: 64, fullName: "Repos 64, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 65, fullName: "Repos 65", isPrivate: true),
            AppleRepos(id: 66, fullName: "Repos 66", isPrivate: true),
            AppleRepos(id: 67, fullName: "Repos 67", isPrivate: true),
            AppleRepos(id: 68, fullName: "Repos 68, This a test to verify if the cell resize by itself", isPrivate: true),
            AppleRepos(id: 69, fullName: "Repos 69", isPrivate: true),
            AppleRepos(id: 70, fullName: "Repos 70", isPrivate: true),
            
        ]
}
